#!/usr/bin/env python3
"""
Build the white, transparent client logos used by the hero marquee.

Input : scripts/sources/<slug>.webp   one tile per client, cropped from the CTO's
                                      logo sheet (6 Oct 2026); flat background
        scripts/originals/<slug>.png  optional original logo (any colour, with alpha);
                                      used instead of the tile when present
Output: public/clients/<slug>.webp    white silhouette + alpha, 4x upscaled, trimmed

The alpha of a tile logo comes from its colour distance to the tile background,
is upscaled, then re-sharpened, so edges stay crisp at retina sizes.

Usage: python3 scripts/build-client-logos.py
"""
import glob
import os

import numpy as np
from PIL import Image, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCES = os.path.join(HERE, "sources")
ORIGINALS = os.path.join(HERE, "originals")
OUT = os.path.join(HERE, "..", "public", "clients")
SIZES_TS = os.path.join(HERE, "..", "src", "data", "clientLogoSizes.ts")
SCALE = 4
# Logos with a large solid fill: keep the dark detail inside the fill as a cut-out.
KNOCKOUT = {"pln", "trip-tour"}
# Detailed emblems: opacity follows darkness (line-art look) instead of a flat silhouette.
LUMA = {"smk-angkasa", "mabes-tni-al"}
# Round emblem above a wordmark: cut the lighter monogram out of the emblem only.
EMBLEM_CUTOUT = {"grand-mercure"}
# Light lettering on a solid box: keep only the lettering.
LETTERING = {"whsmith"}


def smoothstep(x, a, b):
    t = np.clip((x - a) / (b - a), 0, 1)
    return t * t * (3 - 2 * t)


def extract_alpha(img, slug):
    a = np.asarray(img.convert("RGB")).astype(np.float32)
    a = a[3:-3, 3:-3]  # drop tile edge pixels
    h, w, _ = a.shape
    border = np.concatenate([a[0], a[-1], a[:, 0], a[:, -1]])
    bg = np.median(border, axis=0)
    d = np.sqrt(((a - bg) ** 2).sum(-1))
    d8 = Image.fromarray(np.clip(d, 0, 255).astype(np.uint8))
    d = np.asarray(d8.filter(ImageFilter.GaussianBlur(0.5))).astype(np.float32)
    fg = d[d > 25]
    ref = max(np.percentile(fg, 85) if fg.size > 50 else 120.0, 60.0)
    n = np.clip(d / ref, 0, 1.4)
    lum = (a * np.array([0.299, 0.587, 0.114])).sum(-1)
    if slug in LUMA:
        bg_lum = float((bg * np.array([0.299, 0.587, 0.114])).sum())
        n = np.clip((bg_lum - lum) / bg_lum * 1.7, 0, 1) ** 0.85 * np.clip(d / (0.35 * ref), 0, 1)
    elif slug in EMBLEM_CUTOUT:
        top = np.zeros_like(lum, dtype=bool)
        top[: int(h * 0.56)] = True
        fill = np.percentile(lum[(d > 0.6 * ref) & top], 25)
        cut = np.clip(1.0 - np.clip(lum - fill, 0, None) / 55.0, 0.0, 1.0)
        n = n * np.where(top, cut, 1.0)
    elif slug in LETTERING:
        box = d > 0.6 * ref
        ys, xs = np.where(box)
        inside = np.zeros_like(box)
        inside[ys.min() + 3:ys.max() - 2, xs.min() + 3:xs.max() - 2] = True
        fill = np.percentile(lum[box], 40)
        n = np.clip((lum - fill) / (255 - fill) * 1.3, 0, 1) * inside
    elif slug in KNOCKOUT:
        fill = np.percentile(lum[d > 0.6 * ref], 80)
        n = n * np.clip((lum - 0.45 * fill) / (0.55 * fill), 0.0, 1.0) ** 0.7
    big = Image.fromarray((np.clip(n, 0, 1) * 255).astype(np.uint8)).resize(
        (w * SCALE, h * SCALE), Image.LANCZOS
    )
    return smoothstep(np.asarray(big).astype(np.float32) / 255, 0.16, 0.62)


def to_white_rgba(alpha):
    h, w = alpha.shape
    out = np.zeros((h, w, 4), np.uint8)
    out[..., :3] = 255
    out[..., 3] = (alpha * 255).astype(np.uint8)
    return Image.fromarray(out)


def trim(img, pad):
    bbox = img.getchannel("A").point(lambda v: 255 if v > 24 else 0).getbbox()
    if not bbox:
        return img
    x0, y0, x1, y1 = bbox
    return img.crop((max(0, x0 - pad), max(0, y0 - pad),
                     min(img.width, x1 + pad), min(img.height, y1 + pad)))


def main():
    os.makedirs(OUT, exist_ok=True)
    sizes = {}
    for path in sorted(glob.glob(os.path.join(SOURCES, "*.webp"))):
        slug = os.path.splitext(os.path.basename(path))[0]
        orig = os.path.join(ORIGINALS, slug + ".png")
        if os.path.exists(orig):
            alpha = np.asarray(Image.open(orig).convert("RGBA").getchannel("A")).astype(np.float32) / 255
        else:
            alpha = extract_alpha(Image.open(path), slug)
        logo = trim(to_white_rgba(alpha), 2 * SCALE)
        logo.save(os.path.join(OUT, slug + ".webp"), "WEBP", quality=95, method=6)
        sizes[slug] = logo.size
        print(f"{slug:24s} {logo.size[0]}x{logo.size[1]}")
    lines = [
        "// Generated by scripts/build-client-logos.py - do not edit by hand.",
        "// Pixel size [width, height] of each file in public/clients.",
        "export const clientLogoSizes: Record<string, [number, number]> = {",
    ]
    lines += [f"  '{k}': [{w}, {h}]," for k, (w, h) in sorted(sizes.items())]
    lines.append("}")
    with open(SIZES_TS, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
