import { clientLogoSizes } from '@/data/clientLogoSizes'

/**
 * Client logos shown in the hero marquee (ClientCarousel.vue).
 * Source: client logo sheet from the CTO (6 Oct 2026). The white, transparent files in
 * public/clients are generated by scripts/build-client-logos.py.
 */
export interface ClientLogoItem {
  name: string
  file: string
}

const light = (name: string, file: string): ClientLogoItem => ({ name, file })
const dark = light

const items: ClientLogoItem[] = [
  light('Otoritas Jasa Keuangan', 'ojk'),
  light('Direktorat Jenderal Pajak', 'djp'),
  light('PLN', 'pln'),
  light('Perhutani', 'perhutani'),
  light('Mabes TNI AL', 'mabes-tni-al'),
  light('CIMB Niaga', 'cimb-niaga'),
  light('Tirta Musi', 'tirta-musi'),
  light('Bank TKI (BPR Tata Karya Indonesia)', 'bank-tki'),
  light('AQUA', 'aqua'),
  light('DENSO', 'denso'),
  light('Honda', 'honda'),
  light('Indomobil', 'indomobil'),
  light('Dunex Logistics Solution', 'dunex'),
  light('Trip Tour', 'trip-tour'),
  light('Goldenbird', 'goldenbird'),
  light('UP PKJ TIM', 'up-pkj-tim'),
  light('Rumah Sehat untuk Jakarta RSUD Tugu Koja', 'rumah-sehat-jakarta'),
  light('Mitra Keluarga', 'mitra-keluarga'),
  light('San Medical Center', 'san-medical-center'),
  light('Brawijaya Hospital Saharjo', 'brawijaya-hospital'),
  light('Pro Mitra Analitika', 'pro-mitra-analitika'),
  light('UNTAR', 'untar'),
  light('SMK Angkasa', 'smk-angkasa'),
  light('Mallesso', 'mallesso'),
  light('Swiss-Belhotel Danum Palangka Raya', 'swiss-belhotel-danum'),
  light('WHSmith', 'whsmith'),
  light('Grand Mercure', 'grand-mercure'),
  light('Gamma Scientific', 'gamma-scientific'),
  dark('The Westin Jakarta', 'the-westin-jakarta'),
  dark('Trinland', 'trinland'),
  dark("Hariom's", 'hariom-s'),
  dark('7.AM | 7.PM', '7am-7pm'),
  dark('Sumak', 'sumak'),
]

// Equal visual weight: a logo's height follows its aspect ratio, so wide wordmarks
// and round emblems look the same size. Heights are in px at desktop scale.
const LOGO_AREA = 5600
const MIN_HEIGHT = 26
const MAX_HEIGHT = 58
const MAX_WIDTH = 176

export const clientLogos = items.map((item) => {
  const [w, h] = clientLogoSizes[item.file]
  const aspect = w / h
  const height = Math.round(
    Math.min(MAX_HEIGHT, Math.max(MIN_HEIGHT, Math.sqrt(LOGO_AREA / aspect)), MAX_WIDTH / aspect),
  )
  return {
    ...item,
    src: `/clients/${item.file}.webp`,
    width: w,
    height: h,
    displayHeight: height,
  }
})
